export const data = [
  {
    id: 1,
    image: "/images/booqnb-preview.png",
    title: "booQnb",
    techs: ["Next.js", "TailwindCSS", "Prisma", "MongoDB", "shadcnUI"],
    live_url: "https://booqnb.vercel.app",
    code_url: "https://github.com/codezeloss",
  },
  {
    id: 2,
    image: "/images/cipiux-preview.png",
    title: "Cipiux",
    techs: ["Next.js", "TailwindCSS", "Prisma", "MongoDB", "shadcnUI"],
    live_url: "https://cipiux.vercel.app",
    code_url: "https://github.com/codezeloss",
  },
  {
    id: 3,
    image: "/images/albatross-preview.png",
    title: "albatross",
    techs: ["Next.js", "TailwindCSS", "Prisma", "MongoDB", "shadcnUI"],
    live_url: "https://albatross-manager.vercel.app/",
    code_url: "https://github.com/codezeloss",
  },
  {
    id: 4,
    image: "/images/countries-preview.jpg",
    title: "Countries Search App",
    techs: ["Typescript", "Next.js", "TailwindCSS", "API"],
    live_url: "https://rest-countries-api-weld.vercel.app/",
    code_url: "https://github.com/codezeloss",
  },
  {
    id: 5,
    image: "/images/photosnap-preview.jpg",
    title: "Photosnap website",
    techs: ["Typescript", "Next.js", "TailwindCSS"],
    live_url: "https://photosnap-multi-page-website-n4xu.vercel.app/",
    code_url: "https://github.com/codezeloss",
  },
  {
    id: 6,
    image: "/images/githubsearch-preview.jpg",
    title: "GitHub search app",
    techs: ["Reactjs", "TailwindCSS", "API"],
    live_url: "https://aesthetic-maamoul-737009.netlify.app/",
    code_url: "https://github.com/elosscode",
  },
  {
    id: 7,
    image: "/images/planetsfacts-preview.jpg",
    title: "Planets Facts website",
    techs: ["Typescript", "Next.js", "TailwindCSS"],
    live_url: "https://planets-fact-site-pi.vercel.app/",
    code_url: "https://github.com/elosscode",
  },
];
